name: Run Python Script

on:
  schedule:
    - cron: "0 * * * *"  # Hər saatda bir işlə (cron sintaksisi)
  workflow_dispatch:  # Manual olaraq işə salmaq üçün

jobs:
  run-script:
    runs-on: ubuntu-latest  # Ubuntu ən son versiyasında işləyir

    steps:
      # 1. Reponu klonla
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Python quraşdır
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Python 3.9 istifadə et

      # 3. Tələb olunan kitabxanaları quraşdır
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # 4. Python skriptini işə sal
      - name: Run Python script
        run: python yodaaz.py  # Skriptin adını dəyişdirin
